name = "worker-online-message"
main = "src/index.js"
compatibility_date = "2025-12-04"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "online-message-board"
database_id = "de566895-8597-4697-98b9-6b06f36d0925"  #  D1 数据库 ID

# Rules for importing HTML file
[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true
